stages:
  - images
  - build
  - package
  - release

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/gams_transfer_r/${CI_COMMIT_TAG}/"

image_linux:
    stage: images
    tags:
        - linux
    image:
        name: docker:latest
    services:
        - docker:dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - mkdir -p $HOME/.docker
        - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
    script:
        - docker build -t linux/builder images/linux
        - docker tag linux/builder registry.gams.com/devel/gams-transfer-r/linux/builder:latest
        - docker push registry.gams.com/devel/gams-transfer-r/linux/builder:latest
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
          changes:
            - images/linux/Dockerfile
          when: manual
          allow_failure: true

build_r_linux_binary:
    stage: build
    tags:
        - linux
    image: 
        name: registry.gams.com/devel/gams-transfer-r/linux/builder
    script:
        - R CMD INSTALL gamstransfer --build
        - mkdir binary
        - mv gamstransfer_*.tar.gz binary/gamstransfer_r_linux.tar.gz
    only:
        - merge_requests
        - main
        - tags
    artifacts:
        name: gamstransfer_r_linux
        paths:
            - binary
        expire_in: 1 day

build_r_source:
    stage: build
    tags:
        - linux
    image:
        name: registry.gams.com/devel/gams-transfer-r/linux/builder
    script:
        - R CMD build gamstransfer
        - mkdir source
        - mv gamstransfer_*.tar.gz source/gamstransfer_r.tar.gz
    only:
        - merge_requests
        - main
        - tags
    artifacts:
        name: gamstransfer_r
        paths:
            - source
        expire_in: 1 day

# build_r_macos:
#     stage: build
#     tags:
#         - macos
#     script:
#         - R CMD INSTALL gamstransfer --build
#         - mkdir binary
#         - mv gamstransfer_*.tgz binary/gamstransfer_r_macos.tgz
#     only:
#         - merge_requests
#         - main
#         - tags
#     artifacts:
#         name: gams_transfer_r_macos
#         paths:
#             - r_macos
#         expire_in: 1 day

# build_r_windows:
#     stage: build
#     tags:
#         - windows-shell
#     script:
#         - cd gamstransfer
#         - Rscript -e "devtools::build(binary=TRUE)"
#         - Rscript -e "devtools::build(binary=TRUE)"
#         - cd ..
#         - mkdir binary
#         - mv gamstransfer_*.zip binary/gamstransfer_r_windows.zip
#     only:
#         - merge_requests
#         - main
#         - tags
#     artifacts:
#         name: gams_transfer_r_windows
#         paths:
#             - r_windows
#         expire_in: 1 day

package:
    stage: package
    tags:
        - linux
    image:
        name: registry.gams.com/devel/gams-transfer-r/linux/builder
    script:
        - cd source
        - | 
            curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file gamstransfer_r.tar.gz ${PACKAGE_REGISTRY_URL}
        - cd ..
        - cd binary
        - |
            curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file gamstransfer_r_linux.tar.gz ${PACKAGE_REGISTRY_URL}
        - cd ..
        # - |
        #     curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file gamstransfer_r_windows.zip ${PACKAGE_REGISTRY_URL}
        
        # - |
        #     curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file gamstransfer_r_macos.tgz ${PACKAGE_REGISTRY_URL}
    only:
        - tags

release:
    stage: release
    tags:
        - linux
    image:
        name: registry.gams.com/devel/gams-transfer-r/linux/builder
    script:
        - DESCR=$(grep -Pzo "(?s)GAMS Transfer R $CI_COMMIT_TAG.*?((?=\nGAMS Transfer R v)|$)" CHANGELOG | tr -d '\0')
        - |
            curl --header \
            --data '{ "name": "Release $CI_COMMIT_TAG", "tag_name": $CI_COMMIT_TAG, "description": "$DESCR", "assets": { "links": [{ "name": "gamstransfer_r.tar.gz", "url": ${PACKAGE_REGISTRY_URL}gamstransfer_r.tar.gz}] } }'\
            --data '{ "name": "Release $CI_COMMIT_TAG", "tag_name": $CI_COMMIT_TAG, "description": "$DESCR", "assets": { "links": [{ "name": "gamstransfer_r_linux.tar.gz", "url": ${PACKAGE_REGISTRY_URL}gamstransfer_r_linux.tar.gz}] } }'\
            "JOB-TOKEN: ${CI_JOB_TOKEN}" ${PACKAGE_REGISTRY_URL}              
    only:
        - tags
