stages:
  - images
  - build
  - package
  - release

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/gams_transfer_r/${CI_COMMIT_TAG}/"

image_linux:
    stage: images
    tags:
        - linux
    image:
        name: docker:20.10
    services:
        - docker:20.10-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - mkdir -p $HOME/.docker
        - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
    script:
        - docker build -t linux/builder images/linux
        - docker tag linux/builder registry.gams.com/devel/gams-transfer-r/linux/builder:latest
        - docker push registry.gams.com/devel/gams-transfer-r/linux/builder:latest
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
          changes:
            - images/linux/Dockerfile
          when: manual
          allow_failure: true

# build_r_linux_binary:
#     stage: build
#     tags:
#         - linux
#     # image:
#     #     name: registry.gams.com/devel/gams-transfer-r/linux/builder
#     script:
#         - mkdir binary
#         - cd binary
#         - R CMD INSTALL gamstransfer --build
#         - mv gamstransfer_*.tar.gz gamstransfer_r_linux.tar.gz
#         - cd ..
#     only:
#         - merge_requests
#         - main
#         - tags
#     artifacts:
#         name: gamstransfer_r_linux.tar.gz
#         paths:
#             - binary
#         expire_in: 1 day

# build_r_source:
#     stage: build
#     tags:
#         - linux
#     # image:
#     #     name: registry.gams.com/devel/gams-transfer-r/linux/builder
#     script:
#         - mkdir source
#         - cd source
#         - R CMD build gamstransfer
#         - mv gamstransfer_*.tar.gz gamstransfer_r.tar.gz
#         - cd ..
#     only:
#         - merge_requests
#         - main
#         - tags
#     artifacts:
#         name: gamstransfer_r_linux.tar.gz
#         paths:
#             - source
#         expire_in: 1 day

# build_r_macos:
#     stage: build
#     tags:
#         - macos
#     script:
#         - R CMD INSTALL gamstransfer --build
#     only:
#         - merge_requests
#         - master
#         - tags
#     artifacts:
#         name: gams_transfer_r_macos
#         paths:
#             - r_macos
#         expire_in: 1 day

build_r_windows:
    stage: build
    tags:
        - windows
    script:
        - mkdir windows_binary
        - cd windows_binary
        - R CMD INSTALL gamstransfer --build
        - mv gamstransfer_*.zip gamstransfer_r_windows.zip
        - cd ..
    only:
        - merge_requests
        - master
        - tags
    artifacts:
        name: gams_transfer_r_windows
        paths:
            - r_windows
        expire_in: 1 day

package:
    stage: package
    tags:
        - linux
    image:
        name: registry.gams.com/devel/gams-transfer-r/linux/builder
    script:

        # - | 
        #     curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file gamstransfer_r.tar.gz ${PACKAGE_REGISTRY_URL}
        
        # - |
        #     curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file gamstransfer_r_linux.tar.gz ${PACKAGE_REGISTRY_URL}
        
        - |
            curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file gamstransfer_r_windows.zip ${PACKAGE_REGISTRY_URL}
    only:
        - tags

release:
    stage: release
    tags:
        - linux
    image:
        name: registry.gams.com/devel/gams-transfer-r/linux/builder
    script:
        - | 
            release-cli create \
                --name "Release $CI_COMMIT_TAG" \
                --tag-name $CI_COMMIT_TAG \
                # --assets-link "{\"name\":\"gamstransfer_r_linux.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}gamstransfer_r_linux.tar.gz\"}" \
                --assets-link "{\"name\":\"gamstransfer_r_windows.zip\",\"url\":\"${PACKAGE_REGISTRY_URL}gamstransfer_r_windows.zip\"}"
                # --assets-link "{\"name\":\"gamstransfer_r.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}gamstransfer_r.tar.gz\"}"
    only:
        - tags
