stages:
  - fetch-scripts
  - fetch
  - install-gams
  - images
  - build
  - test
  - package
  - release

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/gams_transfer_r/${CI_COMMIT_TAG}/"
  MACHINES_CONTAINER_REG:
      value: registry.gams.com/devel/machines
      description: "URL to the container registry of the machines repository"
  PF_CUSTOM_BRANCH:
      value: "0"
      description: "Name of custom branch, or X.Y.Z for published distribution, or 0 if version is specified in text file with lines GAMS_DISTRIB_MAJOR=X, GAMS_DISTRIB_MINOR=Y, GAMS_DISTRIB_GOLD=Z"
  PF_BUILDS_WWW_PATH:
      value: $BUILDS_WWW_PATH
      description: "URL path prefix for builds server"
  PF_BUILDS_SSH_PORT:
      value: $BUILDS_SSH_PORT
      description: "Port used for SSH connection to builds server"
  PF_BUILDS_SSH_SERVER:
      value: $BUILDS_SSH_SERVER
      description: "URL of the build server"
  PF_BUILDS_SSH_USER:
      value: $BUILDS_SSH_USER
      description: "Username used for SSH connection to builds server"
  PF_GAMS_LICENSE:
      value: $GAMS_LICENSE
      description: "GAMS license string used for testing"

fetch-ci-scripts:
  stage: fetch-scripts
  only:
    - merge_requests
    - main
    - tags
  tags: [linux]
  dependencies: []
  image:
    name: $MACHINES_CONTAINER_REG/leg/builder-full:latest
    entrypoint: [ "" ]
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.gams.com/devel/ciscripts.git scripts-repo
    - cp -R scripts-repo/ci .
  artifacts:
    name: ci-scripts
    expire_in: 2 hours
    paths: [ci/*]

fetch-gamsdist-for-wei:
  stage: fetch
  only:
    - merge_requests
    - main
    - tags
  when: on_success
  tags: [linux]
  dependencies: [fetch-ci-scripts]
  image:
    name: $MACHINES_CONTAINER_REG/leg/builder-full:latest
    entrypoint: [ "" ]
  script:
    - python3 ci/fetch_gams.py fetch_wei $PF_CUSTOM_BRANCH $SSH_KEY_PORTING force
    - python3 ci/fetch_gams.py fetch_wei $PF_CUSTOM_BRANCH $SSH_KEY_PORTING buildInfo
  artifacts:
    name: wei-installer
    expire_in: 15 minutes
    paths: [windows_x64_64.exe,buildInfo.txt]

install-gamsdist-leg:
  stage: install-gams
  only:
    - merge_requests
    - main
    - tags
  tags: [linux]
  dependencies: [fetch-ci-scripts]
  image:
    name: $MACHINES_CONTAINER_REG/leg/builder-full:latest
    entrypoint: [""]
  script:
    - python3 ci/fetch_gams.py fetch_and_install_leg $PF_CUSTOM_BRANCH $SSH_KEY_PORTING
    - /cache/gams-installs/`python3 ci/fetch_gams.py version`/gams
    - python3 ci/fetch_gams.py version
  artifacts:
    name: leg-gmsdirpath
    expire_in: 15 minutes
    paths: [mygmsdir.tmp]

install-gamsdist-deg:
  stage: install-gams
  only:
    - merge_requests
    - main
    - tags
  when: on_success
  tags: [macos]
  dependencies: [fetch-ci-scripts]
  script:
    - python3 ci/fetch_gams.py fetch_and_install_deg $PF_CUSTOM_BRANCH $SSH_KEY_PORTING
    - $HOME/cache/gams-installs/`python3 ci/fetch_gams.py version`/gams

install-gamsdist-arm64:
  stage: install-gams
  only:
    - merge_requests
    - main
    - tags
  when: on_success
  tags: [macos-arm64]
  dependencies: [fetch-ci-scripts]
  script:
    - python3 ci/fetch_gams.py fetch_and_install_dac $PF_CUSTOM_BRANCH $SSH_KEY_PORTING
    - $HOME/cache/gams-installs/`python3 ci/fetch_gams.py version`/gams

install-gamsdist-wei:
  stage: install-gams
  when: on_success
  only:
    - merge_requests
    - main
    - tags
  tags: [windows]
  dependencies: [fetch-gamsdist-for-wei,fetch-ci-scripts]
  image:
    name: $MACHINES_CONTAINER_REG/wei/builder-full:latest
  script:
    - python ci/fetch_gams.py install $PF_CUSTOM_BRANCH $SSH_KEY_PORTING
    - python ci/fetch_gams.py version
    - $gmsdirname = Get-Content mygmsdir.tmp -Raw
    - Invoke-Expression "& 'C:\\Cache\\gams-installs\\$gmsdirname\\gams.exe'"
  artifacts:
    name: wei-gmsdirpath
    expire_in: 15 minutes
    paths: [mygmsdir.tmp]

image_linux:
    stage: images
    tags:
        - linux
    image:
        name: docker:latest
    services:
        - docker:dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - mkdir -p $HOME/.docker
        - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
    script:
        - docker build -t linux/builder images/linux
        - docker tag linux/builder registry.gams.com/devel/gams-transfer-r/linux/builder:latest
        - docker push registry.gams.com/devel/gams-transfer-r/linux/builder:latest
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
          changes:
            - images/linux/Dockerfile
          when: manual
          allow_failure: true

image_windows:
  stage: images
  tags:
    - windows-shell
  script:
    - docker build -t $CI_REGISTRY_IMAGE/windows/builder images/windows
    - docker push $CI_REGISTRY_IMAGE/windows/builder
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - images/windows/Dockerfile
      when: manual
      allow_failure: true


build_r_linux_binary:
    stage: build
    tags:
        - linux
    needs: [install-gamsdist-leg]
    image: 
        name: registry.gams.com/devel/gams-transfer-r/linux/builder
    script:
        - R CMD INSTALL gamstransfer --build
        - mkdir binary
        - mv gamstransfer_*.tar.gz binary/gamstransfer_r_linux.tar.gz
    only:
        - merge_requests
        - main
        - tags
    artifacts:
        name: gamstransfer_r_linux
        paths:
            - binary
        expire_in: 1 day

build_r_source:
    stage: build
    tags:
        - linux
    needs: [install-gamsdist-leg]
    image:
        name: registry.gams.com/devel/gams-transfer-r/linux/builder
    script:
        - R CMD build gamstransfer
        - mkdir source
        - mv gamstransfer_*.tar.gz source/gamstransfer_r.tar.gz
    only:
        - merge_requests
        - main
        - tags
    artifacts:
        name: gamstransfer_r
        paths:
            - source
        expire_in: 1 day

build_r_macos:
    stage: build
    tags:
        - macos
    needs: [install-gamsdist-deg]
    script:
        - mkdir -p $CI_PROJECT_DIR/myinstalldir
        - R CMD INSTALL gamstransfer --build -l $CI_PROJECT_DIR/myinstalldir
        - mv gamstransfer_*.tgz gamstransfer_r_macos.tgz
    only:
        - merge_requests
        - main
        - tags
    artifacts:
        name: gams_transfer_r_macos
        paths: [gamstransfer_r_macos.tgz]
        expire_in: 1 day

build_r_macos_arm64:
    stage: build
    tags:
        - macos-arm64
    needs: [install-gamsdist-arm64]
    script:
        - mkdir -p $CI_PROJECT_DIR/myinstalldir
        - R CMD INSTALL gamstransfer --build -l $CI_PROJECT_DIR/myinstalldir
        - mv gamstransfer_*.tgz gamstransfer_r_macos_arm64.tgz
    only:
        - merge_requests
        - main
        - tags
    artifacts:
        name: gams_transfer_r_macos_arm64
        paths: [gamstransfer_r_macos_arm64.tgz]
        expire_in: 1 day

build_r_windows:
    stage: build
    tags: [windows]
    needs: [install-gamsdist-wei]
    image:
        name: registry.gams.com/devel/gams-transfer-r/windows/builder
    script:
        - C:\'Program Files'\R\R-4.2.1\bin\R.exe CMD build gamstransfer
        - C:\'Program Files'\R\R-4.2.1\bin\R.exe CMD INSTALL gamstransfer --build
        - mv gamstransfer_*.zip gamstransfer_r_windows.zip
    only:
        - merge_requests
        - main
        - tags
    artifacts:
        name: gams_transfer_r_windows
        paths: [gamstransfer_r_windows.zip]
        expire_in: 1 day

test_r_linux:
    stage: test
    tags:
        - linux
    image:
        name: registry.gams.com/devel/gams-transfer-r/linux/builder
    script:
        - PATH=/cache/gams-installs/`cat mygmsdir.tmp`:$PATH
        - echo $PATH
        - R CMD check ./gamstransfer --no-manual --no-tests
        - Rscript -e "install.packages('source/gamstransfer_r.tar.gz')"
        - Rscript -e "testthat::test_dir('gamstransfer/tests')"
    needs: [fetch-ci-scripts,install-gamsdist-leg,build_r_linux_binary,build_r_source]
    only:
        - merge_requests
        - main
        - tags

test_r_macos:
    stage: test
    tags:
        - macos
    script:
        - PATH=$HOME/cache/gams-installs/`python3 ci/fetch_gams.py version`:$PATH
        - DYLD_LIBRARY_PATH=$HOME/cache/gams-installs/`python3 ci/fetch_gams.py version`:$DYLD_LIBRARY_PATH
        - echo $PATH
        - R CMD check ./gamstransfer --no-manual
    needs: [fetch-ci-scripts,install-gamsdist-deg,build_r_macos,build_r_source]
    only:
        - merge_requests
        - main
        - tags

test_r_macos_arm64:
    stage: test
    tags:
        - macos-arm64
    script:
        - PATH=$HOME/cache/gams-installs/`python3 ci/fetch_gams.py version`:$PATH
        - DYLD_LIBRARY_PATH=$HOME/cache/gams-installs/`python3 ci/fetch_gams.py version`:$DYLD_LIBRARY_PATH
        - echo $PATH
        - R CMD check ./gamstransfer --no-manual
    needs: [fetch-ci-scripts,install-gamsdist-arm64,build_r_macos_arm64,build_r_source]
    only:
        - merge_requests
        - main
        - tags

test_r_windows:
    stage: test
    tags: [windows]
    needs: [fetch-ci-scripts,install-gamsdist-wei,build_r_windows,build_r_source]
    image:
        name: registry.gams.com/devel/gams-transfer-r/windows/builder
    script:
        - $gmsdirname = Get-Content mygmsdir.tmp -Raw
        - $GAMS_PATH = "C:\Cache\gams-installs\$gmsdirname"
        - $env:Path = "$GAMS_PATH;$GAMS_PATH\gbin;" + $env:Path
        - echo $env:PATH
        - mv gamstransfer_r_windows.zip gamstransfer.zip
        - Rscript -e "install.packages('gamstransfer.zip', type='binary')"; $null
        - C:\'Program Files'\R\R-4.2.1\bin\Rscript.exe -e "testthat::test_dir('gamstransfer/tests')"; $null
    only:
        - merge_requests
        - main
        - tags

package:
    stage: package
    tags:
        - linux
    image:
        name: registry.gams.com/devel/gams-transfer-r/linux/builder
    script:
        - cd source
        - | 
            curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file gamstransfer_r.tar.gz ${PACKAGE_REGISTRY_URL}
        - cd ..
        - cd binary
        - |
            curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file gamstransfer_r_linux.tar.gz ${PACKAGE_REGISTRY_URL}
        - cd ..
        - |
            curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file gamstransfer_r_windows.zip ${PACKAGE_REGISTRY_URL}

        - |
            curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file gamstransfer_r_macos.tgz ${PACKAGE_REGISTRY_URL}
        - |
            curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file gamstransfer_r_macos_arm64.tgz ${PACKAGE_REGISTRY_URL}
    only:
        - tags

release_job:
    stage: release
    tags:
        - linux
    image:
        name: registry.gams.com/devel/gams-transfer-r/linux/builder
    script:

        - DESCR=$(grep -Pzo "(?s)GAMS Transfer R $CI_COMMIT_TAG.*?((?=\nGAMS Transfer R v)|$)" CHANGELOG | tr -d '\0')
        - |
            release-cli create \
                --name "Release $CI_COMMIT_TAG" \
                --tag-name $CI_COMMIT_TAG \
                --description "$DESCR" \
                --assets-link "{\"name\":\"gamstransfer_r.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}gamstransfer_r.tar.gz\"}" \
                --assets-link "{\"name\":\"gamstransfer_r_linux.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}gamstransfer_r_linux.tar.gz\"}" \
                --assets-link "{\"name\":\"gamstransfer_r_windows.zip\",\"url\":\"${PACKAGE_REGISTRY_URL}gamstransfer_r_windows.zip\"}" \
                --assets-link "{\"name\":\"gamstransfer_r_macos.tgz\",\"url\":\"${PACKAGE_REGISTRY_URL}gamstransfer_r_macos.tgz\"}" \
                --assets-link "{\"name\":\"gamstransfer_r_macos_arm64.tgz\",\"url\":\"${PACKAGE_REGISTRY_URL}gamstransfer_r_macos_arm64.tgz\"}"
    only:
        - tags
