# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CPP_getSpecialValues <- function(gdxName, sysDir) {
    .Call(`_gamstransfer_CPP_getSpecialValues`, gdxName, sysDir)
}

CPP_gdxWriteSuper <- function(data, sysDir, fileName, uel_priority, is_uel_priority, compress) {
    invisible(.Call(`_gamstransfer_CPP_gdxWriteSuper`, data, sysDir, fileName, uel_priority, is_uel_priority, compress))
}

CPP_readSuper <- function(symNames, gdxName, sysDir, records, symisnull) {
    .Call(`_gamstransfer_CPP_readSuper`, symNames, gdxName, sysDir, records, symisnull)
}

