# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gdxReadTrial <- function() {
    invisible(.Call(`_gtr_gdxReadTrial`))
}

setList <- function(gdxName) {
    .Call(`_gtr_setList`, gdxName)
}

parameterList <- function(gdxName) {
    .Call(`_gtr_parameterList`, gdxName)
}

getParameters <- function(gdxName) {
    .Call(`_gtr_getParameters`, gdxName)
}

getSpecialValues <- function(gdxName, sysDir) {
    .Call(`_gtr_getSpecialValues`, gdxName, sysDir)
}

getSymbols <- function(gdxName, sysDir) {
    .Call(`_gtr_getSymbols`, gdxName, sysDir)
}

gdxWriteSuper <- function(data, sysDir) {
    invisible(.Call(`_gtr_gdxWriteSuper`, data, sysDir))
}

gdxWriteTrial <- function(df, sym, sysDir, Dim, varTypeS) {
    invisible(.Call(`_gtr_gdxWriteTrial`, df, sym, sysDir, Dim, varTypeS))
}

readSymbol <- function(symName, gdxName, sysDir) {
    .Call(`_gtr_readSymbol`, symName, gdxName, sysDir)
}

