# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getSpecialValues <- function(gdxName, sysDir) {
    .Call(`_gtr_getSpecialValues`, gdxName, sysDir)
}

checkAcronyms <- function(gdxName, sysDir) {
    .Call(`_gtr_checkAcronyms`, gdxName, sysDir)
}

getSymbols <- function(gdxName, sysDir) {
    .Call(`_gtr_getSymbols`, gdxName, sysDir)
}

gdxWriteSuper <- function(data, sysDir, fileName) {
    invisible(.Call(`_gtr_gdxWriteSuper`, data, sysDir, fileName))
}

readSymbols <- function(symNames, gdxName, sysDir) {
    .Call(`_gtr_readSymbols`, symNames, gdxName, sysDir)
}

