// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getSpecialValues
List getSpecialValues(CharacterVector gdxName, CharacterVector sysDir);
RcppExport SEXP _gtr_getSpecialValues(SEXP gdxNameSEXP, SEXP sysDirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type gdxName(gdxNameSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sysDir(sysDirSEXP);
    rcpp_result_gen = Rcpp::wrap(getSpecialValues(gdxName, sysDir));
    return rcpp_result_gen;
END_RCPP
}
// checkAcronyms
List checkAcronyms(CharacterVector gdxName, CharacterVector sysDir);
RcppExport SEXP _gtr_checkAcronyms(SEXP gdxNameSEXP, SEXP sysDirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type gdxName(gdxNameSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sysDir(sysDirSEXP);
    rcpp_result_gen = Rcpp::wrap(checkAcronyms(gdxName, sysDir));
    return rcpp_result_gen;
END_RCPP
}
// getSymbolNames
List getSymbolNames(CharacterVector gdxName, CharacterVector sysDir);
RcppExport SEXP _gtr_getSymbolNames(SEXP gdxNameSEXP, SEXP sysDirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type gdxName(gdxNameSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sysDir(sysDirSEXP);
    rcpp_result_gen = Rcpp::wrap(getSymbolNames(gdxName, sysDir));
    return rcpp_result_gen;
END_RCPP
}
// getSymbols
List getSymbols(CharacterVector gdxName, CharacterVector sysDir);
RcppExport SEXP _gtr_getSymbols(SEXP gdxNameSEXP, SEXP sysDirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type gdxName(gdxNameSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sysDir(sysDirSEXP);
    rcpp_result_gen = Rcpp::wrap(getSymbols(gdxName, sysDir));
    return rcpp_result_gen;
END_RCPP
}
// gdxWriteSuper
void gdxWriteSuper(List data, CharacterVector sysDir, CharacterVector fileName);
RcppExport SEXP _gtr_gdxWriteSuper(SEXP dataSEXP, SEXP sysDirSEXP, SEXP fileNameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sysDir(sysDirSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type fileName(fileNameSEXP);
    gdxWriteSuper(data, sysDir, fileName);
    return R_NilValue;
END_RCPP
}
// readSymbols
List readSymbols(CharacterVector symNames, CharacterVector gdxName, CharacterVector sysDir);
RcppExport SEXP _gtr_readSymbols(SEXP symNamesSEXP, SEXP gdxNameSEXP, SEXP sysDirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type symNames(symNamesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type gdxName(gdxNameSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sysDir(sysDirSEXP);
    rcpp_result_gen = Rcpp::wrap(readSymbols(symNames, gdxName, sysDir));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gtr_getSpecialValues", (DL_FUNC) &_gtr_getSpecialValues, 2},
    {"_gtr_checkAcronyms", (DL_FUNC) &_gtr_checkAcronyms, 2},
    {"_gtr_getSymbolNames", (DL_FUNC) &_gtr_getSymbolNames, 2},
    {"_gtr_getSymbols", (DL_FUNC) &_gtr_getSymbols, 2},
    {"_gtr_gdxWriteSuper", (DL_FUNC) &_gtr_gdxWriteSuper, 3},
    {"_gtr_readSymbols", (DL_FUNC) &_gtr_readSymbols, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_gtr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
